name: notbit

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: contains(toJson(github.event.commits), '[skip ci]') == false
    needs: create_release
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey
        key: ${{ runner.os }}-chocolatey-${{ matrix.os }}

    - name: Install packages
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get install -y autoconf automake gcc

    - name: Install packages (macos)
      if: startsWith(matrix.os, 'mac')
      run: |
        brew install tor openssl
        brew install pkg-config autoconf automake

    - name: Install choco packages (Windows)
      if: startsWith(matrix.os, 'windows')
      run: |
        choco install cygwin
      shell: bash

    - name: Install cygwin packages
      if: startsWith(matrix.os, 'windows')
      run: |
        C:\tools\cygwin\cygwinsetup.exe -qgnNdO -R C:/tools/cygwin -s http://mirrors.kernel.org/sourceware/cygwin/ -P autoconf,automake,gcc-core,libssl1.1,make,patch
      shell: cmd

    - name: Cygwin cleanup
      if: startsWith(matrix.os, 'windows')
      run: |
        # Rename cygwin's bash
        mv "C:\tools\cygwin\bin\bash.exe" "C:\tools\cygwin\bin\bashcyg.exe"
      shell: bash

    - name: OS-specific vars (win)
      if: startsWith(matrix.os, 'windows')
      run: |
        echo "C:\tools\cygwin\bin" >> $GITHUB_PATH
        echo "C:\tools\cygwin\usr\bin" >> $GITHUB_PATH
      shell: bash

    - name: Compile notbit
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        ./autogen.sh --prefix=$GITHUB_WORKSPACE
        make
        make install
        mkdir lib
        find /usr/lib -iname 'libcrypto.so*' -exec cp -av {} lib \;
        tar -czvf notbit.tar.gz bin lib
      shell: bash

    - name: Compile notbit (windows)
      if: startsWith(matrix.os, 'windows')
      run: |
        export SHELLOPTS
        rm -f /cygdrive/c/Program\ Files/Git/usr/bin/autopoint*
        ./autogen.sh --prefix=$GITHUB_WORKSPACE
        make
      shell: bashcyg -eo igncr {0}

    - uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: config.log
        path: config.log

    - name: Release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_name: notbit.tar.gz
        asset_path: notbit.tar.gz
        asset_content_type: application/octet-stream

  create_release:
    if: contains(toJson(github.event.commits), '[skip ci]') == false
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Release config
        id: release_config
        run: |
          echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "TAGNAME=continuous-${GITHUB_REF##*/}" >> $GITHUB_ENV
        shell: bash

      - name: Create release
        id: create_release
        uses: actions/create-release@v1

        with:
          prerelease: true
          tag_name: ${{ env.TAGNAME}}
          release_name: Notbit
          draft: false
